from MyFractal import MyFractal
a = MyFractal(1, 3)
print(a)
b = MyFractal (1, 2)
print (a + b)
c = MyFractal (1, 8)
print (a - c)
print (a + 23)
d = MyFractal (1, 4)
print (a * d)
print (a * 3)
e = MyFractal (3, 2)
print (a / e)
print (a / 4)